{ lib, ... }: {
  imports = [
    ../../users/fortibrine.nix
    ../../profiles/dhcp.nix
    ../../profiles/podman.nix
    ../../profiles/tailscale.nix
    ../../apps/vaultwarden.nix
    ../../common/bundle.nix
  ];

  boot.growPartition = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.timeout = 0;

  users.users.fortibrine.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH0YU4hRk8CoImqmTClWknO2lrYXjWcT6YgxuAw8z9I0"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIJI3JLFNgAlmM4kyn2E6xc8dmkXXiHE8s2hB2B4KDSs Generated By Termius"
  ];
  networking.hostName = "oracle-server1";

  services.openssh.openFirewall = lib.mkForce false;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";

}
