{ lib, ... }: {
  imports = [
    ../../users/fortibrine.nix
    ../../profiles/cloud-init-network.nix
    ../../profiles/tailscale.nix
    ../../profiles/podman.nix
    ../../common/bundle.nix
  ];

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/vda";

  users.users.fortibrine.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLnn5VH5w5k/gAGGYhcZLVdZnKES+OqJauiA14uv3OZ fortibrine@opensuse"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICFHaAncAaiyVSyZx5H8OFKAEUoZ18bPdFnxjXGxFSAA Generated By Termius"
  ];
  networking.hostName = "mexican-pearl18408";
  time.timeZone = "Europe/Warsaw";

  services.openssh.openFirewall = lib.mkForce false;
  services.tailscale.useRoutingFeatures = "server";

  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  system.stateVersion = "26.05";

}
